<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="bin\Debug\net8.0\Libreria.Application.deps.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\Debug\Libreria.Application.1.0.0.nupkg" />
    <None Include="bin\Debug\net8.0\Libreria.Application.dll" />
    <None Include="bin\Debug\net8.0\Libreria.Application.pdb" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
